<div style="text-align: center; background-color: #750E21; font-family: 'Trebuchet MS', Arial, sans-serif; color: white; padding: 20px; font-size: 40px; font-weight: bold; border-radius: 0 0 0 0; box-shadow: 0px 6px 8px rgba(0, 0, 0, 0.2);">
  FINAL PROJECT: RESEARCHING ON MUSIC TASTE WORDWIDELY üìå
</div>

<div style="text-align: center; background-color: #0766AD; font-family: 'Trebuchet MS', Arial, sans-serif; color: white; padding: 20px; font-size: 40px; font-weight: bold; border-radius: 0 0 0 0; box-shadow: 0px 6px 8px rgba(0, 0, 0, 0.2);">
  Stage 02 - Preprocessing üìå
</div>

## Import

In [12]:
import numpy as np
import pandas as pd
from datetime import datetime

## Exploring data

### Read raw data from file

In [61]:
raw_df = pd.read_csv('../data/raw/final_raw_data.csv')
raw_df.head()

,Id,View,Like,Duration,Channel_name,Subscriber,Country,Publish_time,Hasgtag,Title,Most view per day,Most-view-date,Highest rank,Time to Highest rank,Charted-duration,Song Name,Artist Name,Release Date (Spotify),Popularity Score (Spotify),Genre
0,9bZkp7q19f0,4.977100e+09,27830052.0,0:04:13,officialpsy,18400000.0,NaN,2012-07-15 07:46:32,4.0,PSY - GANGNAM STYLE(Í∞ïÎÇ®Ïä§ÌÉÄÏùº) M/V,14924298,2012/12/21,1.0,36.0,482.0,Gangnam Style (Í∞ïÎÇ®Ïä§ÌÉÄÏùº),PSY,2012-01-01,75,"['k-rap', 'korean old school hip hop']"
1,hT_nvWreIhg,3.927344e+09,17491157.0,0:04:44,OneRepublicVEVO,5470000.0,NaN,2013-05-31 07:00:36,2.0,OneRepublic - Counting Stars,3288973,2018/11/10,4.0,NaN,482.0,Counting Stars,OneRepublic,2013-01-01,88,['panamanian pop']
2,JGwWNGJdvx8,6.149237e+09,32323841.0,0:04:24,Ed Sheeran,53900000.0,NaN,2017-01-30 10:57:50,3.0,Ed Sheeran - Shape of You (Official Music Video),14390704,2017/05/13,1.0,4.0,356.0,Shape of You,Ed Sheeran,2017-03-03,88,"['colombian pop', 'dance pop', 'latin pop', 'p..."
3,lp-EO5I60KA,3.700048e+09,14912926.0,0:04:57,Ed Sheeran,53900000.0,NaN,2014-10-07 13:57:37,3.0,Ed Sheeran - Thinking Out Loud (Official Music...,3771622,2015/02/14,3.0,1.0,304.0,Thinking out Loud,Ed Sheeran,2014-06-21,85,"['latin pop', 'puerto rican pop']"
4,CevxZvSJLk8,3.918655e+09,16596026.0,0:04:30,KatyPerryVEVO,24600000.0,US,2013-09-05 20:00:22,0.0,Katy Perry - Roar,11294380,2013/09/07,2.0,5.0,445.0,Roar,Katy Perry,2013-10-18,74,"['canadian pop', 'pop']"

### How many rows and how many columns does the raw data have?

First, we need to check the number of rows and columns to see if our data has at least 5 fields and 1000 observations.

In [62]:
shape = raw_df.shape

In [63]:
# TEST
print(f"Current shape: {shape}")

if ((shape[0] >= 1000) & (shape[1] >= 5)):
    print(f"Our data is good!.")
else:
    print(f"May be we need to crawl data again.!")

Current shape: (2500, 20)
Our data is good!.

### What does each line mean? Does it matter if the lines have different meanings?

Understand the meaning of each line gives us a more overall understanding of the data. What our data is talking about or .   
If some lines of data have different meanings, it will lead to the unconsistency of data and giving wrong insights.

In our data, each line contains data of a music song on both youtube and spotify platform.

### Does the raw data have duplicate rows?

We need to check for the duplicated rows since these rows don't have much meaning. Each line should differ from each others. Having duplicated rows could lead to wrong insights for questions required couting.

In [64]:
index = raw_df.index
detectDupSeries = index.duplicated(keep='first')
num_duplicated_rows = detectDupSeries.sum()

In [65]:
print(f'Number of duplicated rows: {num_duplicated_rows}')

Number of duplicated rows: 0

Since our data doesn't contain duplicate rows, we don't need to remove them.

### What does each column mean?

Id:   
View:   
Like:   
Duration:   
Channel_name:   
Subscriber:   
Country:   
Publish_time:   
Hashtag:   
Title:   
Most view per day:   
Most-view-date:   
Highest rank:   
Time to Highest rank:    
Charted-duration:    
Song name:   
Artist name:   
Release Date (Spotify):   
Popularity Score (Spotify):   
Genre:

Since `Song name` and `Artist name` have already contains information of `Title` we should then remove this column.

In [66]:
raw_df = raw_df.drop('Title', axis=1)
raw_df

,Id,View,Like,Duration,Channel_name,Subscriber,Country,Publish_time,Hasgtag,Most view per day,Most-view-date,Highest rank,Time to Highest rank,Charted-duration,Song Name,Artist Name,Release Date (Spotify),Popularity Score (Spotify),Genre
0,9bZkp7q19f0,4.977100e+09,27830052.0,0:04:13,officialpsy,18400000.0,NaN,2012-07-15 07:46:32,4.0,14924298,2012/12/21,1.0,36.0,482.0,Gangnam Style (Í∞ïÎÇ®Ïä§ÌÉÄÏùº),PSY,2012-01-01,75,"['k-rap', 'korean old school hip hop']"
1,hT_nvWreIhg,3.927344e+09,17491157.0,0:04:44,OneRepublicVEVO,5470000.0,NaN,2013-05-31 07:00:36,2.0,3288973,2018/11/10,4.0,NaN,482.0,Counting Stars,OneRepublic,2013-01-01,88,['panamanian pop']
2,JGwWNGJdvx8,6.149237e+09,32323841.0,0:04:24,Ed Sheeran,53900000.0,NaN,2017-01-30 10:57:50,3.0,14390704,2017/05/13,1.0,4.0,356.0,Shape of You,Ed Sheeran,2017-03-03,88,"['colombian pop', 'dance pop', 'latin pop', 'p..."
3,lp-EO5I60KA,3.700048e+09,14912926.0,0:04:57,Ed Sheeran,53900000.0,NaN,2014-10-07 13:57:37,3.0,3771622,2015/02/14,3.0,1.0,304.0,Thinking out Loud,Ed Sheeran,2014-06-21,85,"['latin pop', 'puerto rican pop']"
4,CevxZvSJLk8,3.918655e+09,16596026.0,0:04:30,KatyPerryVEVO,24600000.0,US,2013-09-05 20:00:22,0.0,11294380,2013/09/07,2.0,5.0,445.0,Roar,Katy Perry,2013-10-18,74,"['canadian pop', 'pop']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,HC172grgTwU,3.250905e+08,1693226.0,0:05:17,Lokdhun Punjabi,13300000.0,IN,2016-01-18 03:30:00,8.0,216961,2021/02/15,NaN,NaN,NaN,Same Time Tomorrow,Brandon Davis,2023-09-01,23,"['desi pop', 'filmi', 'punjabi pop']"
2496,Fd7lYEtevxQ,3.247416e+08,867653.0,0:03:07,Ruby B·∫£o An,1640000.0,NaN,2011-01-31 13:52:25,8.0,842423,2020/05/01,NaN,NaN,NaN,X√∫c X·∫Øc X√∫c X·∫ª,B√© B·∫£o An,2020-08-08,11,['modern country pop']
2497,Fp8msa5uYsc,3.244410e+08,3355081.0,0:03:33,JustinBieberVEVO,31500000.0,US,2021-10-08 04:00:10,3.0,3261913,2021/10/08,14.0,NaN,10.0,Ghost,Justin Bieber,2021-03-19,89,"['agronejo', 'arrocha', 'sertanejo', 'sertanej..."
2498,6EGg0_l-edc,3.245723e+08,1617971.0,0:03:11,Henrique e Juliano,15800000.0,BR,2021-09-03 15:00:14,0.0,2562984,2022/07/11,56.0,NaN,29.0,A Maior Saudade / Como √â Que A Gente Fica - Ao...,Henrique & Juliano,2023-12-01,52,"['canadian pop', 'pop']"
2499,soC-46cfs_w,3.302852e+08,1052324.0,0:02:37,Maiara e Maraisa,9680000.0,BR,2017-01-13 12:59:09,0.0,1332816,2017/07/22,134.0,NaN,18.0,A Culpa √â Nossa - Ao Vivo,Maiara & Maraisa,2022-12-16,75,"['sertanejo', 'sertanejo pop', 'sertanejo univ..."

### What data type does each column currently have? Are there any columns whose data types are not suitable for further processing?

Next we will take a look at the data type of each column.

In [67]:
dtypes = raw_df.dtypes

In [68]:
dtypes

Id                             object
View                          float64
Like                          float64
Duration                       object
Channel_name                   object
Subscriber                    float64
Country                        object
Publish_time                   object
Hasgtag                       float64
Most view per day               int64
Most-view-date                 object
Highest rank                  float64
Time to Highest rank          float64
Charted-duration              float64
Song Name                      object
Artist Name                    object
Release Date (Spotify)         object
Popularity Score (Spotify)      int64
Genre                          object
dtype: object

`Most-view-date`, `Publish_time` and `Release Date (Spotify)` are problaly date-time data type, so we should convert these 2 columns into date-time.

In [69]:
Most_view_date = []
Publish_time = []
Release_date = []

date_format = ['%Y', '%Y-%m', '%Y-%m-%d']

for date, time, release_date in zip(raw_df['Most-view-date'], raw_df['Publish_time'], raw_df['Release Date (Spotify)']):
    date = np.nan if pd.isna(date) else datetime.strptime(date, '%Y/%m/%d')
    time = np.nan if pd.isna(time) else datetime.strptime(time, '%Y-%m-%d %H:%M:%S')
    if (pd.isna(release_date)):
        release_date = np.nan
    elif ('-' not in (release_date)):
        release_date = datetime.strptime(release_date, '%Y')
    elif (len(release_date) == 7):
        release_date = datetime.strptime(release_date, '%Y-%m')
    else:
        release_date = datetime.strptime(release_date, '%Y-%m-%d')
    
    Most_view_date.append(date)
    Publish_time.append(time)
    Release_date.append(release_date)
    
raw_df['Most-view-date'] = Most_view_date
raw_df['Publish_time'] = Publish_time
raw_df['Release Date (Spotify)'] = Release_date

`View`, `Like`, `Subscriber`, `Hashtag`, `Highest rank`, `Time to Highest rank` and `Charted-duration` can be observes as integer data type. So we should convert these columns into integer.

In [70]:
def convert_to_int(value):
    try:
        return int(value)
    except ValueError:
        return None

raw_df['View'] = raw_df['View'].apply(convert_to_int)
raw_df['Like'] = raw_df['Like'].apply(convert_to_int)
raw_df['Subscriber'] = raw_df['Subscriber'].apply(convert_to_int)
raw_df['Hasgtag'] = raw_df['Hasgtag'].apply(convert_to_int)
raw_df['Highest rank'] = raw_df['Highest rank'].apply(convert_to_int)
raw_df['Time to Highest rank'] = raw_df['Time to Highest rank'].apply(convert_to_int)
raw_df['Charted-duration'] = raw_df['Charted-duration'].apply(convert_to_int)

Now let's take a look again the data types of each column.

In [71]:
raw_df.dtypes

Id                                    object
View                                 float64
Like                                 float64
Duration                              object
Channel_name                          object
Subscriber                           float64
Country                               object
Publish_time                  datetime64[ns]
Hasgtag                              float64
Most view per day                      int64
Most-view-date                datetime64[ns]
Highest rank                         float64
Time to Highest rank                 float64
Charted-duration                     float64
Song Name                             object
Artist Name                           object
Release Date (Spotify)        datetime64[ns]
Popularity Score (Spotify)             int64
Genre                                 object
dtype: object

We can see that although we try to convert the values of these columns into integer, their data types are still float64. This is beacause integer data type doesn't allow for `NaN` so if there is a `NaN` value in the column, the column data type will automatically converted to float.

### For each column with numeric data type, how are the values distributed?

For columns with numeric data types, we will calculate:   
- Percentage (from 0 to 100) of missing values
- The min
- The lower quartile (ph√¢n v·ªã 25)
- The median (ph√¢n v·ªã 50)
- The upper quartile (ph√¢n v·ªã 75)
- The max

First we need to select columns with numeric data type.

In [72]:
num_col_info_df = raw_df.select_dtypes(include='number')

In [73]:
def missing_ratio(s):
    return (s.isna().mean() * 100).round(1)

def median(df):
    return (df.quantile(0.5)).round(1)

def lower_quartile(df):
    return (df.quantile(0.25)).round(1)

def upper_quartile(df):
    return (df.quantile(0.75)).round(1)

In [74]:
num_col_info_df = num_col_info_df.agg([missing_ratio, "min", lower_quartile, median, upper_quartile, "max"])
num_col_info_df

,View,Like,Subscriber,Hasgtag,Most view per day,Highest rank,Time to Highest rank,Charted-duration,Popularity Score (Spotify)
missing_ratio,4.000000e-01,0.5,0.4,0.4,0.0,25.0,87.2,25.0,0.0
min,3.244410e+08,471866.0,7330.0,0.0,141350.0,1.0,1.0,1.0,0.0
lower_quartile,3.982876e+08,2089275.2,2935000.0,0.0,765111.5,6.0,1.0,13.0,59.0
median,5.150177e+08,3129072.0,9160000.0,3.0,1837817.5,21.0,1.0,25.0,71.0
upper_quartile,7.857353e+08,5063792.2,24600000.0,4.0,4233410.5,58.0,3.0,47.0,78.0
max,8.327580e+09,52536744.0,254000000.0,81.0,88851354.0,200.0,36.0,622.0,97.0

After identifying the basic statistical numbers that describe your data, we further need to determine the features that have a large number of missing values. Such features are not useful for the analysis stage and must be removed from the dataset.   
Usually, if the percentage of missing values is greater than 75%, the column is dropped from the dataframe and an updated dataframe is returned.

In [75]:
def drop_missing_features(df: pd.DataFrame, missing_lst: dict = dict(num_col_info_df.iloc[0]), threshold: float = 75.0) -> pd.DataFrame:
    if (df is None) or (missing_lst is None) or (threshold is None):
        print(f"[LOG] Invalid.")
        raise ValueError
    
    # Create a copy of the dataframe to avoid changing the original
    df_cp = df.copy()
    
    # List to maintain the columns to drop
    cols_to_trim = []
    
    for key, value in missing_lst.items():
        if float(value) > threshold:
            cols_to_trim.append(key)
            
    if len(cols_to_trim) > 0:
        # drop the columns identified using the dataframe drop() method
        df_cp = df_cp.drop(columns=cols_to_trim)
        print("[LOG] Dropped column(s): " + " ".join(cols_to_trim))
    else:
        print("[LOG] Have no column(s) to trim.")
        
    return df_cp

In [76]:
raw_df = drop_missing_features(raw_df, dict(num_col_info_df.iloc[0]))

[LOG] Dropped column(s): Time to Highest rank

In [77]:
raw_df.head()

,Id,View,Like,Duration,Channel_name,Subscriber,Country,Publish_time,Hasgtag,Most view per day,Most-view-date,Highest rank,Charted-duration,Song Name,Artist Name,Release Date (Spotify),Popularity Score (Spotify),Genre
0,9bZkp7q19f0,4.977100e+09,27830052.0,0:04:13,officialpsy,18400000.0,NaN,2012-07-15 07:46:32,4.0,14924298,2012-12-21,1.0,482.0,Gangnam Style (Í∞ïÎÇ®Ïä§ÌÉÄÏùº),PSY,2012-01-01,75,"['k-rap', 'korean old school hip hop']"
1,hT_nvWreIhg,3.927344e+09,17491157.0,0:04:44,OneRepublicVEVO,5470000.0,NaN,2013-05-31 07:00:36,2.0,3288973,2018-11-10,4.0,482.0,Counting Stars,OneRepublic,2013-01-01,88,['panamanian pop']
2,JGwWNGJdvx8,6.149237e+09,32323841.0,0:04:24,Ed Sheeran,53900000.0,NaN,2017-01-30 10:57:50,3.0,14390704,2017-05-13,1.0,356.0,Shape of You,Ed Sheeran,2017-03-03,88,"['colombian pop', 'dance pop', 'latin pop', 'p..."
3,lp-EO5I60KA,3.700048e+09,14912926.0,0:04:57,Ed Sheeran,53900000.0,NaN,2014-10-07 13:57:37,3.0,3771622,2015-02-14,3.0,304.0,Thinking out Loud,Ed Sheeran,2014-06-21,85,"['latin pop', 'puerto rican pop']"
4,CevxZvSJLk8,3.918655e+09,16596026.0,0:04:30,KatyPerryVEVO,24600000.0,US,2013-09-05 20:00:22,0.0,11294380,2013-09-07,2.0,445.0,Roar,Katy Perry,2013-10-18,74,"['canadian pop', 'pop']"

After remove features which have large missing values, our dataframe still have missing values. So that, we need to fill these missing values so that they can be used in analysis.  
There's many ways to fill in the missing values. Here we will use the median value of each column to fill in.

In [78]:
def filling_missing_value(df: pd.DataFrame) -> pd.DataFrame:
    df = df.replace({None: np.nan})
    
    if (df is None):
        print(f"[LOG] Invalid.")
        raise ValueError
    
    # Create a copy of the dataframe to avoid changing the original
    df_cp = df.copy()
    
    # Get the list of columns in the dataframe
    cols_list = list(df_cp.columns)
    
    # Exclude the last column - Country, Year
    cols_list.remove("Id")
    cols_list.remove("Duration")
    cols_list.remove("Channel_name")
    cols_list.remove("Publish_time")
    cols_list.remove("Country")
    cols_list.remove("Most-view-date")
    cols_list.remove("Song Name")
    cols_list.remove("Artist Name")
    cols_list.remove("Release Date (Spotify)")
    cols_list.remove("Genre")
    
    # Replace all None values with NaN, fillna only works on nans
    df_cp.fillna(value=np.nan, inplace=True)
    
    # Replace all NaN values with the mean of the column values
    for col in cols_list:
        df_cp[col].fillna((df_cp[col].median()), inplace=True)
        
    return df_cp

In [79]:
raw_df = filling_missing_value(df=raw_df)

In [80]:
raw_df.head()

,Id,View,Like,Duration,Channel_name,Subscriber,Country,Publish_time,Hasgtag,Most view per day,Most-view-date,Highest rank,Charted-duration,Song Name,Artist Name,Release Date (Spotify),Popularity Score (Spotify),Genre
0,9bZkp7q19f0,4.977100e+09,27830052.0,0:04:13,officialpsy,18400000.0,NaN,2012-07-15 07:46:32,4.0,14924298,2012-12-21,1.0,482.0,Gangnam Style (Í∞ïÎÇ®Ïä§ÌÉÄÏùº),PSY,2012-01-01,75,"['k-rap', 'korean old school hip hop']"
1,hT_nvWreIhg,3.927344e+09,17491157.0,0:04:44,OneRepublicVEVO,5470000.0,NaN,2013-05-31 07:00:36,2.0,3288973,2018-11-10,4.0,482.0,Counting Stars,OneRepublic,2013-01-01,88,['panamanian pop']
2,JGwWNGJdvx8,6.149237e+09,32323841.0,0:04:24,Ed Sheeran,53900000.0,NaN,2017-01-30 10:57:50,3.0,14390704,2017-05-13,1.0,356.0,Shape of You,Ed Sheeran,2017-03-03,88,"['colombian pop', 'dance pop', 'latin pop', 'p..."
3,lp-EO5I60KA,3.700048e+09,14912926.0,0:04:57,Ed Sheeran,53900000.0,NaN,2014-10-07 13:57:37,3.0,3771622,2015-02-14,3.0,304.0,Thinking out Loud,Ed Sheeran,2014-06-21,85,"['latin pop', 'puerto rican pop']"
4,CevxZvSJLk8,3.918655e+09,16596026.0,0:04:30,KatyPerryVEVO,24600000.0,US,2013-09-05 20:00:22,0.0,11294380,2013-09-07,2.0,445.0,Roar,Katy Perry,2013-10-18,74,"['canadian pop', 'pop']"

In [82]:
raw_df.select_dtypes(include='number').agg([missing_ratio, "min", lower_quartile, median, upper_quartile, "max"])

,View,Like,Subscriber,Hasgtag,Most view per day,Highest rank,Charted-duration,Popularity Score (Spotify)
missing_ratio,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,3.244410e+08,471866.0,7330.0,0.0,141350.0,1.0,1.0,0.0
lower_quartile,3.985463e+08,2094270.2,2950000.0,0.0,765111.5,9.8,17.0,59.0
median,5.150177e+08,3129072.0,9160000.0,3.0,1837817.5,21.0,25.0,71.0
upper_quartile,7.838052e+08,5046276.8,24600000.0,4.0,4233410.5,44.0,37.0,78.0
max,8.327580e+09,52536744.0,254000000.0,81.0,88851354.0,200.0,622.0,97.0

### For each column with a non-numeric data type, how are the values distributed?

For columns with non-numeric data types, we calculate:

- Percentage (from 0 to 100) of missing values
- Number of values (the values here are different values and we do not consider missing values): with columns whose type is categorical, it is a set with a finite number of categories. Directly counting the number of values in these columns doesn't make much sense, so it's better to count the number of elements of all types. (S·ªë l∆∞·ª£ng c√°c gi√° tr·ªã (c√°c gi√° tr·ªã ·ªü ƒë√¢y l√† c√°c gi√° tr·ªã kh√°c nhau v√† ta kh√¥ng x√©t gi√° tr·ªã thi·∫øu): v·ªõi c·ªôt m√† c√≥ ki·ªÉu l√† categorical, n√≥ l√† m·ªôt t·∫≠p h·ª£p c√≥ s·ªë l∆∞·ª£ng h·ªØu h·∫°n c√°c lo·∫°i. Vi·ªác ƒë·∫øm tr·ª±c ti·∫øp s·ªë l∆∞·ª£ng c√°c gi√° tr·ªã trong nh·ªØng c·ªôt n√†y kh√¥ng c√≥ nhi·ªÅu √Ω nghƒ©a, n√™n t·ªët h∆°n h·∫øt l√† m√† s·∫Ω ƒë·∫øm s·ªë l∆∞·ª£ng ph·∫ßn t·ª≠ c√°c lo·∫°i.)
- The percentage (from 0 to 100) of each value is sorted by decreasing percentage (we do not consider missing values, the ratio is the ratio compared to the number of non-missing values): you use a dictionary to store , key is the value, value is the percentage; With the column corresponding to each type, the method is similar to above.

In [89]:
cat_col_info_df = raw_df.select_dtypes(include='object')

In [90]:
def missing_ratio(s):
    return (s.isna().mean() * 100).round(1)

def num_values(s):
    s = s.str.split(';')
    s = s.explode()
    return len(s.value_counts())

def value_ratios(s):
    s = s.str.split(';')
    s = s.explode()
    totalCount = (~s.isna()).sum()
    return ((s.value_counts()/totalCount*100).round(1)).to_dict()

In [91]:
cat_col_info_df = cat_col_info_df.agg([missing_ratio, num_values, value_ratios])
cat_col_info_df

,Id,Duration,Channel_name,Country,Song Name,Artist Name,Genre
missing_ratio,0.0,0.4,0.4,44.6,0.0,0.0,0.0
num_values,2500,322,893,40,2359,1083,716
value_ratios,"{'9bZkp7q19f0': 0.0, '_EyZUTDAH0U': 0.0, 'f5aD...","{'0:03:54': 1.3, '0:03:38': 1.2, '0:03:55': 1....","{'T-Series': 4.8, 'Zee Music Company': 1.0, 'B...","{'US': 38.4, 'IN': 21.7, 'BR': 8.7, 'PR': 6.4,...","{'Pepas': 0.2, 'I Am Your Gummy Bear (The Gumm...","{'Bad Bunny': 1.0, 'Justin Bieber': 0.9, 'BTS'...","{'[]': 4.4, '['pop']': 4.2, '['filmi', 'modern..."

### Is the collected data reasonable?

### Save processed data

In [92]:
print(f"Total number of features: {raw_df.shape[1]}")
raw_df.dtypes

Total number of features: 18

Id                                    object
View                                 float64
Like                                 float64
Duration                              object
Channel_name                          object
Subscriber                           float64
Country                               object
Publish_time                  datetime64[ns]
Hasgtag                              float64
Most view per day                      int64
Most-view-date                datetime64[ns]
Highest rank                         float64
Charted-duration                     float64
Song Name                             object
Artist Name                           object
Release Date (Spotify)        datetime64[ns]
Popularity Score (Spotify)             int64
Genre                                 object
dtype: object

In [93]:
raw_df.to_csv("../data/processed/music_video_data.csv", index=False)